export declare const wuwaRouteRules: {
    readonly help: RegExp;
    readonly login: RegExp;
    readonly bind: RegExp;
    readonly token: RegExp;
    readonly stamina: RegExp;
    readonly roleinfo: RegExp;
    readonly explore: RegExp;
    readonly sign: RegExp;
    readonly tower: RegExp;
    readonly refresh: RegExp;
};
export declare const WAVES_GAME_ID = 3;
export declare const SERVER_ID = "76402e5b20be2c39f095a152090afddc";
export declare const SERVER_ID_NET = "919752ae5ea09c1ced910dd668a63ffb";
export declare const NET_SERVER_ID_MAP: Record<number, string>;
export declare const KURO_BASE_URL = "https://api.kurobbs.com";
export declare const KURO_API: {
    readonly LOGIN: "https://api.kurobbs.com/user/sdkLogin";
    readonly LOGIN_LOG: "https://api.kurobbs.com/user/login/log";
    readonly ROLE_LIST: "https://api.kurobbs.com/gamer/role/list";
    readonly REFRESH: "https://api.kurobbs.com/aki/roleBox/akiBox/refreshData";
    readonly REQUEST_TOKEN: "https://api.kurobbs.com/aki/roleBox/requestToken";
    readonly GAME_DATA: "https://api.kurobbs.com/gamer/widget/game3/getData";
    readonly BASE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/baseData";
    readonly ROLE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/roleData";
    readonly ROLE_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/getRoleDetail";
    readonly CALABASH_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/calabashData";
    readonly EXPLORE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/exploreIndex";
    readonly SIGN_INIT: "https://api.kurobbs.com/encourage/signIn/initSignInV2";
    readonly SIGN_IN: "https://api.kurobbs.com/encourage/signIn/v2";
    readonly TOWER_INDEX: "https://api.kurobbs.com/aki/roleBox/akiBox/towerIndex";
    readonly TOWER_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/towerDataDetail";
    readonly CHALLENGE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/challengeDetails";
    readonly MINE_V2: "https://api.kurobbs.com/user/mineV2";
};
export declare const KURO_VERSION = "3.0.0";
export declare const IOS_USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) KuroGameBox/3.0.0";
export declare const ANDROID_USER_AGENT = "Mozilla/5.0 (Linux; Android 16; 25098PN5AC Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Mobile Safari/537.36 Kuro/3.0.0 KuroGameBox/3.0.0";
export declare const WAVES_ECHO_COLORS: Record<string, string>;
