export declare const wuwaRouteRules: {
    readonly help: RegExp;
    readonly login: RegExp;
    readonly bind: RegExp;
    readonly token: RegExp;
    readonly stamina: RegExp;
    readonly roleinfo: RegExp;
    readonly explore: RegExp;
    readonly sign: RegExp;
    readonly tower: RegExp;
    readonly challenge: RegExp;
    readonly slash: RegExp;
    readonly matrix: RegExp;
    readonly charlist: RegExp;
    readonly coin: RegExp;
    readonly announce: RegExp;
    readonly code: RegExp;
    readonly gacha: RegExp;
    readonly echoList: RegExp;
    readonly calabash: RegExp;
    readonly period: RegExp;
    readonly calendar: RegExp;
    readonly pool: RegExp;
    readonly refresh: RegExp;
    readonly develop: RegExp;
    readonly poker: RegExp;
    readonly rank: RegExp;
    readonly wiki: RegExp;
};
export declare const WAVES_GAME_ID = 3;
export declare const SERVER_ID = "76402e5b20be2c39f095a152090afddc";
export declare const SERVER_ID_NET = "919752ae5ea09c1ced910dd668a63ffb";
export declare const NET_SERVER_ID_MAP: Record<number, string>;
export declare const KURO_BASE_URL = "https://api.kurobbs.com";
export declare const KURO_API: {
    readonly LOGIN: "https://api.kurobbs.com/user/sdkLogin";
    readonly LOGIN_LOG: "https://api.kurobbs.com/user/login/log";
    readonly ROLE_LIST: "https://api.kurobbs.com/gamer/role/list";
    readonly REFRESH: "https://api.kurobbs.com/aki/roleBox/akiBox/refreshData";
    readonly REQUEST_TOKEN: "https://api.kurobbs.com/aki/roleBox/requestToken";
    readonly GAME_DATA: "https://api.kurobbs.com/gamer/widget/game3/getData";
    readonly BASE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/baseData";
    readonly ROLE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/roleData";
    readonly ROLE_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/getRoleDetail";
    readonly CALABASH_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/calabashData";
    readonly EXPLORE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/exploreIndex";
    readonly SIGN_INIT: "https://api.kurobbs.com/encourage/signIn/initSignInV2";
    readonly SIGN_IN: "https://api.kurobbs.com/encourage/signIn/v2";
    readonly TOWER_INDEX: "https://api.kurobbs.com/aki/roleBox/akiBox/towerIndex";
    readonly TOWER_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/towerDataDetail";
    readonly CHALLENGE_DATA: "https://api.kurobbs.com/aki/roleBox/akiBox/challengeDetails";
    readonly CHALLENGE_INDEX: "https://api.kurobbs.com/aki/roleBox/akiBox/challengeIndex";
    readonly SLASH_INDEX: "https://api.kurobbs.com/aki/roleBox/akiBox/slashIndex";
    readonly SLASH_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/slashDetail";
    readonly MATRIX_INDEX: "https://api.kurobbs.com/aki/roleBox/akiBox/newTowerIndex";
    readonly MATRIX_DETAIL: "https://api.kurobbs.com/aki/roleBox/akiBox/newTowerDetail";
    readonly MINE_V2: "https://api.kurobbs.com/user/mineV2";
    readonly ANN_LIST: "https://api.kurobbs.com/forum/companyEvent/findEventList";
    readonly ANN_DETAIL: "https://api.kurobbs.com/forum/getPostDetail";
    readonly CALC_REFRESH: "https://api.kurobbs.com/aki/calculator/refreshData";
    readonly CALC_ROLE_LIST: "https://api.kurobbs.com/aki/calculator/listRole";
    readonly CALC_OWNED_ROLE: "https://api.kurobbs.com/aki/calculator/ownedRole/roleInfo";
    readonly CALC_CULTIVATE: "https://api.kurobbs.com/aki/calculator/roleCultivateStatus";
    readonly CALC_BATCH_COST: "https://api.kurobbs.com/aki/calculator/batchRoleCost";
    readonly PERIOD_LIST: "https://api.kurobbs.com/aki/resource/period/list";
    readonly PERIOD_MONTH: "https://api.kurobbs.com/aki/resource/month";
    readonly PERIOD_WEEK: "https://api.kurobbs.com/aki/resource/week";
    readonly PERIOD_VERSION: "https://api.kurobbs.com/aki/resource/version";
    readonly WIKI_HOME: "https://api.kurobbs.com/wiki/core/homepage/getPage";
    readonly WIKI_TREE: "https://api.kurobbs.com/wiki/core/catalogue/config/getTree";
    readonly WIKI_ENTRY_DETAIL: "https://api.kurobbs.com/wiki/core/catalogue/item/getEntryDetail";
    readonly MORE_ACTIVITY: "https://api.kurobbs.com/aki/roleBox/akiBox/moreActivity";
};
export declare const GACHA_API_CN = "https://gmserver-api.aki-game2.com/gacha/record/query";
export declare const GACHA_API_NET = "https://gmserver-api.aki-game2.net/gacha/record/query";
export declare const KURO_VERSION = "3.0.0";
export declare const IOS_USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) KuroGameBox/3.0.0";
export declare const ANDROID_USER_AGENT = "Mozilla/5.0 (Linux; Android 16; 25098PN5AC Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/143.0.7499.34 Mobile Safari/537.36 Kuro/3.0.0 KuroGameBox/3.0.0";
export declare const WAVES_ECHO_COLORS: Record<string, string>;
